### ISSUE TITLE
Make use of the new Android N lambdas for the example?

### ISSUE THREAD

**Issue by Syrou** [konmik/Phlux#4]
With the new Android N release, they offer the possibility to use lambdas back to gingerbread. Maybe implement that instead of gradle-retrolambda?

**Comment by konmik** [comment]
Hi Syrou.

Yeh, it is a good idea. Probably one day, when they will finally release the update and it will recommend itself as a workable and reliable solution that fits nicely into workflow, I will switch to it from retrolambda.

**Comment by konmik** [comment]
Here is the discussion, if you're interested: https://www.reddit.com/r/androiddev/comments/4bcyqs/the_dark_side_of_jackjill/
