### ISSUE TITLE
Unable to compile this project in Andorid studio.

### ISSUE THREAD

**Issue by lectricas** [konmik/Phlux#5]
```
Error:Could not find info.android15.phlux:phlux:0.1.0-SNAPSHOT.
Required by:
    konmic:example:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by konmik** [comment]
You need to build the snapshot version first.

Go to gradle.properties, change path to your local maven repo.

Run: gradle clean build uploadArchives

**Comment by vaughandroid** [comment]
Since everything's under one Gradle project, why not just depend on the local modules directly?

i.e. Replace `compile "info.android15.phlux:phlux:$VERSION_NAME"` with `compile project(':phlux')`

**Comment by ml-bright** [comment]
If i did not have local maven repo, How can i do
